name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Check Buildx version for debugging
      - name: Check Buildx version
        run: docker buildx version

      # Build the Docker image with --load to ensure it's available locally
      - name: Build the Docker image
        run: docker buildx build --file Dockerfile --tag adriantandara/zenidro-image:v1 --load .

      - name: List Docker images
        run: docker images

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check Docker Hub login status
        run: docker info

      - name: Push the Docker image
        run: docker push adriantandara/zenidro-image:v1
